### ISSUE TITLE
add function does not accept `tue`

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#161]
**Describe the bug**
Not able to add using `tue`

**To Reproduce**
1. add n/CS2113T Tutorial d/tue st/08:00 et/09:00 des/Topic: Sequence Diagram t/CS2113T t/Tutorial r/normal
2. `invalid command format`

**Expected behavior**
`1 slots added`

<hr>

**Reported by:** @nicholasleeeee
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#25]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. Actually this is not a bug, the shorten form of "tuesday" is resisted as "tues" but that seems to give confusion since the shortened phrases differ so much from each other. E.g. "thursday" is shortened to "thurs". Hence, we will take your suggestion seriously and standardize these shortened variants into three letters, as such "tue" will now be accepted. This change will be coming very shortly !

**Comment by seanieyap** [comment]
This suggestion has been incorporated into the application, now all "days" have the same standard 3 letter short forms, "mon", "tue", "wed", "thu", "fri".
