### ISSUE TITLE
edit does not edit

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#172]
**Describe the bug**
edit does not work when it comes to indexing 

**To Reproduce**
1. `add n/CS2113T Tutorial d/mon st/08:00 et/09:00`
2. `list t/CS2113T`
3. `edit 1 des/Topic: Sequence Diagram`
4. `Invalid Command Format`

**Expected behavior**
`slots edited`

<hr>

**Reported by:** @nicholasleeeee
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#138]</sub>

**Comment by seanieyap** [comment]
Hi, thank you for feedback.

However, the commands input here are incorrect, item 2, "t/CS2113T" does not correspond to the slots added in item 1 as the slots added are not tagged. Perhaps you are trying to tell us that "edit 1 des/Topic: Sequence Diagram" does not work and this is true due to a typo in the user guide.

The prefix for "new description" should have been "ndes/" instead of "des/". This has been fixed, coincidentally, in #157. 

Thank you for pointing this out.
